version: '3.8'

services:
  # PostgreSQL with PostGIS
  db:
    image: postgis/postgis:15-3.3
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basemaps
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Backend API
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/basemaps
      - SECRET_KEY=temporarysecretkeychangeforproduction
      - ENVIRONMENT=development
      - ALLOW_ORIGINS=http://localhost:5173
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "cd /app && 
      alembic upgrade head && 
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  # Frontend
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_API_URL=http://localhost:8000
    command: npm run dev
    depends_on:
      - backend

volumes:
  postgres_data: